// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package particle.ctrl;

public final class Control {
  private Control() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontrol.proto\022\rparticle.ctrl\032\014common.p" +
      "roto\032\nwifi.proto\032\rnetwork.proto\032\014config." +
      "protoP\000P\001P\002P\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          jtycz.simple.mesh.connector.protos.Common.getDescriptor(),
          jtycz.simple.mesh.connector.protos.Wifi.getDescriptor(),
          jtycz.simple.mesh.connector.protos.Network.getDescriptor(),
          jtycz.simple.mesh.connector.protos.Config.getDescriptor(),
        }, assigner);
    jtycz.simple.mesh.connector.protos.Common.getDescriptor();
    jtycz.simple.mesh.connector.protos.Wifi.getDescriptor();
    jtycz.simple.mesh.connector.protos.Network.getDescriptor();
    jtycz.simple.mesh.connector.protos.Config.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
